version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_fastapi
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: *******8
      MYSQL_USER: omar
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
